config/routes.rb
NinetyNineCats::Application.routes.draw do
  resources :cats, only: [
    :index,
    :show,
    :create,
    :new,
    :edit,
    :update
    ]

  resources :cat_requests, only: [
    :index,
    :show,
    :create,
    :new,
    :edit,
    :update
  ] do
      patch 'approve'
      patch 'deny'
    end

  resources :users, :only => [:create, :new, :show]
  resource :session, :only => [:create, :destroy, :new]

  root :to => "users#show"

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  validates_date :birth_date, :on_or_before => lambda { Date.current }

  validates :sex, inclusion: { in: %w(M F) }

  validates :birth_date, :color, :name, :sex, :description,  presence: true

  has_many(
    :requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: "CatRentalRequest",
    dependent: :destroy
  )


  belongs_to(
    :cats,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: "Cat"
  )

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base

  validates :status, inclusion: { in: %w(APPROVED DENIED PENDING) }

  validates :cat_id, :start_date, :end_date, presence: true

  validate :overlapping_approved_requests

  belongs_to :cat, class_name: "CatRentalRequests", foreign_key: :cat_id, primary_key: :id


  def approve!
    self.status = "APPROVED"
  end

  def deny!
    self.status = "DENIED"
  end
  # private

  def overlapping_requests
    query =  <<-SQL
        SELECT
          *
        FROM
          cat_rental_requests
        WHERE
          start_date <= '#{self.end_date}'
          AND end_date >= '#{self.start_date}'
          AND cat_id = #{self.cat_id}
        SQL
    CatRentalRequest::find_by_sql(query)
    #CatRentalRequest.where(
    #  <<-SQL
    #  SELECT
    #    *
    #  FROM
    #    cat_rental_requests
    #  WHERE
    #    start_date <= '#{self.end_date}'
    #    AND end_date >= '#{self.start_date}'
    #    AND cat_id = #{self.cat_id}
    #  SQL
    #)
  end

  def overlapping_approved_requests
    if overlapping_requests.any? { |requests| requests.status == "APPROVED"}
      errors[:approved] << "That cat is already booked for those dates"
    end
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :password_digest, :presence => true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true, :uniqueness => true
  validates :user_name, :presence => true, :uniqueness => true

  validates :session_token, presence: true
  after_initialize :ensure_session_token

  has_many(
    :cats,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: "Cat"
  )

  def self.find_by_credentials(username, password)
    user = User.find_by_user_name(username)
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def password=(unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private
    def ensure_session_token
      self.session_token ||= self.class.generate_session_token
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Expose these methods to the views
  helper_method :current_user, :signed_in?

  private

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end

  def sign_out
    current_user.try(:reset_session_token!)
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end

  def require_signed_out!
    redirect_to user_url(current_user) if signed_in?
  end


end

app/controllers/cat_requests_controller.rb
class CatRequestsController < ApplicationController

  def index
    @rental = CatRentalRequest.all
    render :index
  end

  def create
    @rental = CatRentalRequest.new(rental_params)

    if @rental.save
      redirect_to cat_requests_url
    else
      #flash here
      render :new
    end
  end

  def approve
    CatRentalRequest.find(params[:cat_request_id]).approve!
  end

  def deny
    CatRentalRequest.find(params[:cat_request_id]).deny!
  end

  def rental_params
    params.require(:rental).permit(:cat_id, :start_date, :end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :make_sure_own_cat, :only => [:edit, :update]

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render(
        :json => @cat.errors.full_messages,
        :status => :unprocessable_entity
      )
    end
  end

  def new
    @cat = Cat.new(color: "blue", name: "fill me out", sex: "M", birth_date: "2014-01-01", description: "fill me out")
    render :new
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render(
        :json => @cat.errors.full_messages,
        :status => :unprocessable_entity
      )
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def destroy
    Cat.destroy(params[:id])
  end



  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end

  def make_sure_own_cat
    @cat = Cat.find(params[:id])
    redirect_to new_session_url if current_user.id.nil?
    redirect_to new_session_url unless @cat.user_id == current_user.id
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      user_params[:user_name],
      user_params[:password]
    )

    if @user
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:session).permit(:user_name, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_in!, :only => [:show]
  before_action :require_signed_out!, :only => [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_requests_helper.rb
module CatRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_requests/approve.html.erb
<h1>Approved!</h1>

app/views/cat_requests/index.html.erb
<h1>Here are the cat requests</h1>
<ul>
  <table>
    <tr>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Status</th>
    </tr>
    <% rentals = @rental %>

      <% if !rentals.nil? %>
        <% rentals.each do |cat|%>
      <tr>
        <td><%= cat.start_date %></td>
        <td><%= cat.end_date %></td>
        <td><%= cat.status %></td>
      </tr>
    <% end %>
  <% end  %>
  </table>
</ul>
<%= link_to "All Cats", cats_url %>

app/views/cat_requests/new.html.erb
<h1>Make a new Request</h2>
<% rental = @CatRentalRequest %>
  <form action="/cat_requests" method="post">
    <input type="hidden" name="_method" value="post">

    <input
       name="authenticity_token"
       type="hidden"
       value="<%= form_authenticity_token %>">

    <label for="cat_name">Cat ID</label>
      <input name="rental[cat_id]" id="cat_name" type="text" value="id">

    <label>Enter your dates</label>
    <label for="cat_start_date">Start date</label>
      <input name="rental[start_date]" id="cat_start_date" type="date">

      <br>
    <label for="cat_end_date">End date</label>
        <input name="rental[end_date]" id="cat_end_date" type="date">

      <input type="submit" value="Submit Reuquest!">
  </form>

app/views/cats/_form.html.erb
<h2>Cat form!</h2>

<% if @cat.id.nil?%>
  <% action_field = "/cats" %>
  <% value_field = "post" %>
<% else %>
  <% action_field = cat_url(@cat) %>
  <% value_field = "patch"%>
<% end %>

<form action="<%= action_field %>" method="post">
  <input type="hidden" name="_method" value="<%= value_field %>">

  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <!-- label's `for` attribute connects with the input's `id` attribute-->
  <label for="cat_name">First name</label>
  <!-- input name `cat[name]` means that Rails will nest the `name` attribute
       inside a `cat` hash: `{ :cat => { :name => "gizmo" } }` -->
  <input name="cat[name]" id="cat_name" type="text" value="<%= @cat.description %>">
  <br>

  <!-- this label isn't for anything specific -->
  <label>Sex</label>
  <div>
    <!-- note that both radio buttons have the name `cat[sex]`; that's how
         they are related -->
    <input name="cat[sex]" id="cat_sex_m" type="radio" value="M" <%= "checked" if @cat.sex == "M" %>>
    <label for="cat_sex_m">Male</label>
    <input name="cat[sex]" id="cat_sex_f" type="radio" value="F" <%= "checked" if @cat.sex == "F" %>>
    <label for="cat_sex_f">Female</label>
  </div>
  <br>

  <label for="cat_description">description</label>
  <textarea name="cat[description]" id="cat_description"><%= @cat.description %></textarea>
  <br>

  <label for="color">Coat color</label>
  <!-- dropdown -->
  <select name="cat[color]">
    <!-- `brown` is the value that will be submitted to the server; user is
         displayed "Brown" as the choice -->
      <option  value="blank"></option>

    <option value="brown" <%= "selected" if @cat.color == "brown" %>>Brown</option>
    <option value="black" <%= "selected" if @cat.color == "black" %>>Black</option>
    <option value="blue" <%= "selected" if @cat.color == "blue" %>>Blue</option>

  </select>
  <br>

  <label for="cat_birth_date">Birth date</label>
  <!-- click on the date will launch a date picker -->

  <% year = @cat.birth_date.year.to_s.rjust(4, "0") %>
  <% month = @cat.birth_date.month.to_s.rjust(2, "0") %>
  <% day = @cat.birth_date.day.to_s.rjust(2, "0") %>

  <input name="cat[birth_date]" id="cat_birth_date" type="date"
  value="<%= "#{year}-#{month}-#{day}" %>"></input>

  <input type="submit" value="Build my cat!">

  <!--
    Other uncovered input types:
    hidden field
    check box
    -->
</form>

app/views/cats/edit.html.erb
<h2>Edit your cat</h2>

<%= render "form"  %>

app/views/cats/index.html.erb
<h1>All your cats</h1>
<ul>
  <% @cats.each do |cat| %>
  <li><%= cat.name %> <%= link_to "Show cat", cat_url(cat) %>
  <% end %>

</ul>

<%= link_to "New Cat", new_cat_url %>
<br>
<%= link_to "Cat Requests", cat_requests_url %>
<br>
<%= link_to "New Cat Rental Request", new_cat_request_url %>

app/views/cats/new.html.erb
<h2>Build your cat!</h2>

<%= render "form"  %>

app/views/cats/show.html.erb
<h1>your cat</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Birth date</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Description</th>
    <th>Created_at</th>
    <th>Updated_at</th>
  </tr>
  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.description %></td>
    <td><%= @cat.created_at %></td>
    <td><%= @cat.updated_at %></td>
  </tr>
</table>

<h1>Your cat requests</h1>
<table>
 <tr>
   <th>Request number</th>
   <th>Approve</th>
   <th>Deny</th>
 </tr>
 <% @cat.requests.each do |request|%>
  <tr>
    <td><%= request.id %></td>
    <td>
     <form action="<%= cat_request_approve_url(@cat.id)%>" method="post">
       <input type="hidden" name="_method" value="patch">

       <input
          name="authenticity_token"
          type="hidden"
          value="<%= form_authenticity_token %>">
      <input type="submit" value="Submit Reuquest!">
      </form>
    </td>
    <td>
    <form action="<%= cat_request_deny_url(@cat.id)%>" method="post">
      <input type="hidden" name="_method" value="patch">

      <input
         name="authenticity_token"
         type="hidden"
         value="<%= form_authenticity_token %>">
     <input type="submit" value="Submit Reuquest!">
     </form>
    </td>
  </tr>
  <% end %>
</table>
<br>
<br>
<%= link_to "All Cats", cats_url %>
<br>
<br>
<%= link_to "Edit cat", edit_cat_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewAuthDemo</title>
  </head>
  <body>

    <% if signed_in? %>
    <ul>
      <li>Signed in as: <%= current_user.user_name %></li>
      <li><%= button_to "Sign Out", session_url, :method => :delete %></li>
    </ul>
    <% else %>
    <p>
      <%= link_to "Sign In", new_session_url %> or
      <%= link_to "Sign up", new_user_url %>
    </p>
    <% end %>

    <hr>

    <% if flash[:errors] %>
    <h3>Please fix the following errors:</h3>
    <ul>
      <% flash[:errors].each do |error| %>
      <li><%= error %></li>
      <% end %>
    </ul>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.user_name %></h1>

<p>Hello, dear user!</p>